services:

  cjm.behat.psr7.client:
    class: Symfony\Component\HttpKernel\Client
    arguments:
      - "@cjm.behat.psr7.kernel"

  cjm.behat.psr7.kernel:
    class: Cjm\Behat\Psr7Extension\SymfonyKernel
    arguments:
      - "@cjm.behat.psr7.app"
      - "@cjm.behat.psr7.http_message_bridge.converter"

  cjm.behat.psr7.app:
    class: Cjm\Behat\Psr7Extension\Psr7App
    factory: "cjm.behat.psr7.loader:load"
    arguments:
      - "%cjm.behat.psr7.app%"

  cjm.behat.psr7.loader:
    class: Cjm\Behat\Psr7Extension\AppFile\Loader
    arguments: [] # receives services tagged as cjm.behat.psr7.factory

  cjm.behat.psr7.factory.callback:
    class: Cjm\Behat\Psr7Extension\Callback\AppFactory
    tags:
      - { name: "cjm.behat.psr7.factory" }

  cjm.behat.psr7.http_message_bridge.converter:
    class: Cjm\Behat\Psr7Extension\PsrHttpMessageBridge\SymfonyToPsr7Converter
    arguments:
      - "@cjm.behat.psr7.http_message_bridge.diactoros_factory"
      - "@cjm.behat.psr7.http_message_bridge.http_foundation_factory"

  cjm.behat.psr7.http_message_bridge.diactoros_factory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory

  cjm.behat.psr7.http_message_bridge.http_foundation_factory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory
